---
  kind: "Service"
  apiVersion: "v1"
  metadata:
    name: bootnode
  spec:
    type: NodePort
    selector:
      app: value_mesh
      rank: bootnode
    ports:
      - protocol: TCP
        port: "5000-6000"
        targetPort: "5000-6000"
