---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: bootnode
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: value_mesh
          rank: bootnode
      spec:
        containers:
          - name: node
            image: {IMAGE}
            command:
              - "node"
              - "./src/app.js"
              - "--bootNode=true"
              - "--refreshDirectory=true"
              - "--address=0.0.0.0"
              - "--port="5000-6000""
            ports:
              - containerPort: "5000-6000"
            resources:
              requests:
                cpu: "100m"
