---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: peernode
  spec:
    replicas: 2
    revisionHistoryLimit: 2
    template:
      metadata:
        labels:
          app: value_mesh
          rank: peernode
      spec:
        containers:
          - name: node
            image: {IMAGE}
            command:
              - "node"
              - "./src/app.js"
              - "--port=80"
              - "--address=0.0.0.0"
              - "--leader=bootnode:80"
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: "100m"
