---
  kind: "Service"
  apiVersion: "v1"
  metadata:
    name: peernode
  spec:
    type: NodePort
    selector:
      app: value_mesh
    ports:
      - protocol: TCP
        port: "5000-6000"
        targetPort: "5000-6000"
